image: docker:latest
services:
  - docker

stages:
  - build
  - package
  - security

build:
  stage: build
  image: golang:1.25.6
  script:
    - apt update
    - apt install npm -y
    - make build-go
  artifacts:
    paths:
      - converter-service

docker-build:
  stage: package
  script:
   - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
   - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
   - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
